"""initial schema

Revision ID: 5a465b992006
Revises: 
Create Date: 2026-07-23 08:46:46.869477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a465b992006'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('WATER', 'CONFECTIONERY', 'DAIRY', 'PET_FOOD', 'PREPARED_FOODS', name='plantcategory'), nullable=False),
    sa.Column('capacity_tons_per_day', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spare_parts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('equipment_type', sa.Enum('FILLER', 'CAPPER', 'LABELER', 'CONVEYOR', 'MIXER', 'PACKAGING', 'PASTEURIZER', 'HOMOGENIZER', 'DRYER', name='equipmenttype'), nullable=False),
    sa.Column('qty_on_hand', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('abc_class', sa.Enum('A', 'B', 'C', name='abcclass'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_lines',
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('line_type', sa.String(length=50), nullable=False),
    sa.Column('speed_units_per_min', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'DOWN', 'CHANGEOVER', 'CIP', 'IDLE', 'MAINTENANCE', name='linestatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_lines_plant_id'), 'production_lines', ['plant_id'], unique=False)
    op.create_table('products',
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('units_per_batch', sa.Integer(), nullable=False),
    sa.Column('changeover_minutes', sa.Float(), nullable=False),
    sa.Column('allergens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_plant_id'), 'products', ['plant_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('shifts',
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('pattern', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_plant_id'), 'shifts', ['plant_id'], unique=False)
    op.create_table('equipment',
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('equipment_type', sa.Enum('FILLER', 'CAPPER', 'LABELER', 'CONVEYOR', 'MIXER', 'PACKAGING', 'PASTEURIZER', 'HOMOGENIZER', 'DRYER', name='equipmenttype'), nullable=False),
    sa.Column('mtbf_hours', sa.Float(), nullable=False),
    sa.Column('mttr_hours', sa.Float(), nullable=False),
    sa.Column('position_in_line', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_line_id'), 'equipment', ['line_id'], unique=False)
    op.create_table('oee_records',
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.Column('performance', sa.Float(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('oee', sa.Float(), nullable=False),
    sa.Column('shift', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oee_records_line_timestamp', 'oee_records', ['line_id', 'timestamp'], unique=False)
    op.create_table('operators',
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_employee_id'), 'operators', ['employee_id'], unique=True)
    op.create_index(op.f('ix_operators_plant_id'), 'operators', ['plant_id'], unique=False)
    op.create_table('production_runs',
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_qty', sa.Integer(), nullable=False),
    sa.Column('actual_qty', sa.Integer(), nullable=False),
    sa.Column('good_qty', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_production_runs_line_start', 'production_runs', ['line_id', 'start_time'], unique=False)
    op.create_table('downtime_events',
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downtime_type', sa.Enum('MECHANICAL', 'ELECTRICAL', 'PROCESS', 'CHANGEOVER', 'CIP', 'PLANNED_MAINTENANCE', 'OTHER', name='downtimetype'), nullable=False),
    sa.Column('root_cause', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downtime_events_line_id'), 'downtime_events', ['line_id'], unique=False)
    op.create_table('maintenance_tasks',
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'PREDICTIVE', 'CONDITION_BASED', name='maintenancetype'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maintenance_tasks_equip_date', 'maintenance_tasks', ['equipment_id', 'scheduled_date'], unique=False)
    op.create_table('skill_matrix',
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=False),
    sa.Column('certified_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_matrix_line_id'), 'skill_matrix', ['line_id'], unique=False)
    op.create_index(op.f('ix_skill_matrix_operator_id'), 'skill_matrix', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_matrix_operator_id'), table_name='skill_matrix')
    op.drop_index(op.f('ix_skill_matrix_line_id'), table_name='skill_matrix')
    op.drop_table('skill_matrix')
    op.drop_index('ix_maintenance_tasks_equip_date', table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_downtime_events_line_id'), table_name='downtime_events')
    op.drop_table('downtime_events')
    op.drop_index('ix_production_runs_line_start', table_name='production_runs')
    op.drop_table('production_runs')
    op.drop_index(op.f('ix_operators_plant_id'), table_name='operators')
    op.drop_index(op.f('ix_operators_employee_id'), table_name='operators')
    op.drop_table('operators')
    op.drop_index('ix_oee_records_line_timestamp', table_name='oee_records')
    op.drop_table('oee_records')
    op.drop_index(op.f('ix_equipment_line_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_shifts_plant_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_plant_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_production_lines_plant_id'), table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_table('spare_parts')
    op.drop_table('plants')
    # ### end Alembic commands ###
